spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_jpa?createDatabaseIfNotExist=true
    username: root
    password: Duggu@123
  flyway:
    baseline-on-migrate: true

stripe:
  appUrl: https://api.stripe.com
  enabled: true
  timeout: 1000
  supported-currencies: USD, EUR, GBP

payment-gateway: paypal

email:
  server-port: 8080
  server-host: serverHost
